<?php

namespace ContainerUBj6la3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZmbzqvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zmbzqv_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zmbzqv_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\CategoryController::index' => ['privates', '.service_locator.a_g.BOa.App\\Controller\\Admin\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\Admin\\CategoryController::delete' => ['privates', '.service_locator.dsbOFwy.App\\Controller\\Admin\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\Admin\\ProductController::index' => ['privates', '.service_locator.mQ2gXFd.App\\Controller\\Admin\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\Admin\\ProductController::new' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\Admin\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\Admin\\ProductController::edit' => ['privates', '.service_locator.49z5AbU.App\\Controller\\Admin\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\Admin\\ProductController::delete' => ['privates', '.service_locator.49z5AbU.App\\Controller\\Admin\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\Admin\\UserController::index' => ['privates', '.service_locator.zXOlprV.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController::new' => ['privates', '.service_locator.TIy7jfb.App\\Controller\\Admin\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\Admin\\UserController::edit' => ['privates', '.service_locator.S3UCmng.App\\Controller\\Admin\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\Front\\CartController::index' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\Front\\CartController::add' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\Front\\CartController::decrease' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::decrease()', 'getCartControllerdecreaseService', true],
            'App\\Controller\\Front\\CartController::remove' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\Front\\CartController::empty' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::empty()', 'getCartControlleremptyService', true],
            'App\\Controller\\Front\\HomeController::index' => ['privates', '.service_locator.mQ2gXFd.App\\Controller\\Front\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\Front\\HomeController::show' => ['privates', '.service_locator.mQ2gXFd.App\\Controller\\Front\\HomeController::show()', 'getHomeControllershowService', true],
            'App\\Controller\\Front\\OrderController::index' => ['privates', '.service_locator.IcZAD61.App\\Controller\\Front\\OrderController::index()', 'getOrderControllerindexService', true],
            'App\\Controller\\Front\\OrderController::confirmation' => ['privates', '.service_locator.ZLzisLB.App\\Controller\\Front\\OrderController::confirmation()', 'getOrderControllerconfirmationService', true],
            'App\\Controller\\Security\\RegistrationController::register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\Security\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\Security\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.fdTWzgN.App\\Controller\\Security\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\Security\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\Security\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\CategoryController:index' => ['privates', '.service_locator.a_g.BOa.App\\Controller\\Admin\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\Admin\\CategoryController:delete' => ['privates', '.service_locator.dsbOFwy.App\\Controller\\Admin\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\Admin\\ProductController:index' => ['privates', '.service_locator.mQ2gXFd.App\\Controller\\Admin\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\Admin\\ProductController:new' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\Admin\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\Admin\\ProductController:edit' => ['privates', '.service_locator.49z5AbU.App\\Controller\\Admin\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\Admin\\ProductController:delete' => ['privates', '.service_locator.49z5AbU.App\\Controller\\Admin\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\Admin\\UserController:index' => ['privates', '.service_locator.zXOlprV.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController:new' => ['privates', '.service_locator.TIy7jfb.App\\Controller\\Admin\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\Admin\\UserController:edit' => ['privates', '.service_locator.S3UCmng.App\\Controller\\Admin\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\Front\\CartController:index' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\Front\\CartController:add' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\Front\\CartController:decrease' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::decrease()', 'getCartControllerdecreaseService', true],
            'App\\Controller\\Front\\CartController:remove' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\Front\\CartController:empty' => ['privates', '.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::empty()', 'getCartControlleremptyService', true],
            'App\\Controller\\Front\\HomeController:index' => ['privates', '.service_locator.mQ2gXFd.App\\Controller\\Front\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\Front\\HomeController:show' => ['privates', '.service_locator.mQ2gXFd.App\\Controller\\Front\\HomeController::show()', 'getHomeControllershowService', true],
            'App\\Controller\\Front\\OrderController:index' => ['privates', '.service_locator.IcZAD61.App\\Controller\\Front\\OrderController::index()', 'getOrderControllerindexService', true],
            'App\\Controller\\Front\\OrderController:confirmation' => ['privates', '.service_locator.ZLzisLB.App\\Controller\\Front\\OrderController::confirmation()', 'getOrderControllerconfirmationService', true],
            'App\\Controller\\Security\\RegistrationController:register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\Security\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\Security\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.fdTWzgN.App\\Controller\\Security\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\Security\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\Security\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\CategoryController::index' => '?',
            'App\\Controller\\Admin\\CategoryController::delete' => '?',
            'App\\Controller\\Admin\\ProductController::index' => '?',
            'App\\Controller\\Admin\\ProductController::new' => '?',
            'App\\Controller\\Admin\\ProductController::edit' => '?',
            'App\\Controller\\Admin\\ProductController::delete' => '?',
            'App\\Controller\\Admin\\UserController::index' => '?',
            'App\\Controller\\Admin\\UserController::new' => '?',
            'App\\Controller\\Admin\\UserController::edit' => '?',
            'App\\Controller\\Front\\CartController::index' => '?',
            'App\\Controller\\Front\\CartController::add' => '?',
            'App\\Controller\\Front\\CartController::decrease' => '?',
            'App\\Controller\\Front\\CartController::remove' => '?',
            'App\\Controller\\Front\\CartController::empty' => '?',
            'App\\Controller\\Front\\HomeController::index' => '?',
            'App\\Controller\\Front\\HomeController::show' => '?',
            'App\\Controller\\Front\\OrderController::index' => '?',
            'App\\Controller\\Front\\OrderController::confirmation' => '?',
            'App\\Controller\\Security\\RegistrationController::register' => '?',
            'App\\Controller\\Security\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\Security\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\CategoryController:index' => '?',
            'App\\Controller\\Admin\\CategoryController:delete' => '?',
            'App\\Controller\\Admin\\ProductController:index' => '?',
            'App\\Controller\\Admin\\ProductController:new' => '?',
            'App\\Controller\\Admin\\ProductController:edit' => '?',
            'App\\Controller\\Admin\\ProductController:delete' => '?',
            'App\\Controller\\Admin\\UserController:index' => '?',
            'App\\Controller\\Admin\\UserController:new' => '?',
            'App\\Controller\\Admin\\UserController:edit' => '?',
            'App\\Controller\\Front\\CartController:index' => '?',
            'App\\Controller\\Front\\CartController:add' => '?',
            'App\\Controller\\Front\\CartController:decrease' => '?',
            'App\\Controller\\Front\\CartController:remove' => '?',
            'App\\Controller\\Front\\CartController:empty' => '?',
            'App\\Controller\\Front\\HomeController:index' => '?',
            'App\\Controller\\Front\\HomeController:show' => '?',
            'App\\Controller\\Front\\OrderController:index' => '?',
            'App\\Controller\\Front\\OrderController:confirmation' => '?',
            'App\\Controller\\Security\\RegistrationController:register' => '?',
            'App\\Controller\\Security\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\Security\\SecurityController:login' => '?',
        ]);
    }
}
