<?php

namespace ContainerUBj6la3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerconfirmationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZLzisLB.App\Controller\Front\OrderController::confirmation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZLzisLB.App\\Controller\\Front\\OrderController::confirmation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.ZLzisLB.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.ZLzisLB": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
        ], [
            'order' => 'App\\Entity\\Order',
        ]))->withContext('App\\Controller\\Front\\OrderController::confirmation()', $container);
    }
}
