<?php

namespace ContainerUBj6la3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EntityListener\OrderListener' shared autowired service.
     *
     * @return \App\EntityListener\OrderListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EntityListener/OrderListener.php';

        return $container->privates['App\\EntityListener\\OrderListener'] = new \App\EntityListener\OrderListener();
    }
}
