<?php

namespace ContainerUBj6la3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IcZAD61.App\Controller\Front\OrderController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IcZAD61.App\\Controller\\Front\\OrderController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'cartService' => ['privates', 'App\\Service\\CartService', 'getCartServiceService', true],
            'orderService' => ['privates', 'App\\Service\\OrderService', 'getOrderServiceService', true],
        ], [
            'em' => '?',
            'cartService' => 'App\\Service\\CartService',
            'orderService' => 'App\\Service\\OrderService',
        ]))->withContext('App\\Controller\\Front\\OrderController::index()', $container);
    }
}
