<?php

namespace ContainerUBj6la3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EntityListener\ProductListener' shared autowired service.
     *
     * @return \App\EntityListener\ProductListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EntityListener/ProductListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        return $container->privates['App\\EntityListener\\ProductListener'] = new \App\EntityListener\ProductListener(($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('fr')));
    }
}
