<?php

namespace ContainerUBj6la3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.49z5AbU.App\Controller\Admin\ProductController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.49z5AbU.App\\Controller\\Admin\\ProductController::delete()'] = ($container->privates['.service_locator.49z5AbU'] ?? $container->load('get_ServiceLocator_49z5AbUService'))->withContext('App\\Controller\\Admin\\ProductController::delete()', $container);
    }
}
