<?php

namespace Container4JSCxYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControlleremptyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KQF_kLz.App\Controller\Front\CartController::empty()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQF_kLz.App\\Controller\\Front\\CartController::empty()'] = ($container->privates['.service_locator.KQF_kLz'] ?? $container->load('get_ServiceLocator_KQFKLzService'))->withContext('App\\Controller\\Front\\CartController::empty()', $container);
    }
}
