<?php

namespace Container4JSCxYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSuperAdminCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateSuperAdminCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateSuperAdminCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-super-admin', ['a:c:a'], 'Create a Super Administrator', false, #[\Closure(name: 'App\\Command\\CreateSuperAdminCommand')] fn (): \App\Command\CreateSuperAdminCommand => ($container->privates['App\\Command\\CreateSuperAdminCommand'] ?? $container->load('getCreateSuperAdminCommandService')));
    }
}
