<?php

namespace Container4JSCxYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSuperAdminCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateSuperAdminCommand' shared autowired service.
     *
     * @return \App\Command\CreateSuperAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateSuperAdminCommand.php';

        $container->privates['App\\Command\\CreateSuperAdminCommand'] = $instance = new \App\Command\CreateSuperAdminCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-super-admin');
        $instance->setAliases(['a:c:a']);
        $instance->setDescription('Create a Super Administrator');

        return $instance;
    }
}
