<?php

namespace Container4JSCxYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\InvoiceService' shared autowired service.
     *
     * @return \App\Service\InvoiceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/InvoiceService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\Service\\InvoiceService'])) {
            return $container->privates['App\\Service\\InvoiceService'];
        }

        return $container->privates['App\\Service\\InvoiceService'] = new \App\Service\InvoiceService($a, ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
