<?php

namespace Container4JSCxYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllervalidatedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pmyYcSl.App\Controller\Front\OrderController::validated()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pmyYcSl.App\\Controller\\Front\\OrderController::validated()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'invoiceService' => ['privates', 'App\\Service\\InvoiceService', 'getInvoiceServiceService', true],
        ], [
            'repository' => 'App\\Repository\\OrderRepository',
            'emailService' => 'App\\Service\\EmailService',
            'em' => '?',
            'invoiceService' => 'App\\Service\\InvoiceService',
        ]))->withContext('App\\Controller\\Front\\OrderController::validated()', $container);
    }
}
