<?php

namespace Container4JSCxYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OrderService' shared autowired service.
     *
     * @return \App\Service\OrderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OrderService.php';

        $a = ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService'));

        if (isset($container->privates['App\\Service\\OrderService'])) {
            return $container->privates['App\\Service\\OrderService'];
        }

        return $container->privates['App\\Service\\OrderService'] = new \App\Service\OrderService($a);
    }
}
